# comment

version: 0.1

phases:
  install:
    commands:
      - echo "this is the install phase"
  build:
    commands:
      - echo "this is the build phase"
      - npm install
      - ls -l
      - cd public && ls -l

      # checking aws version
      - aws --version
      - aws s3 ls
      - cd public && aws s3 sync . s3://pipel.sample/ -acl public_read

      # - aws s3 sync _site/ s3://alexbilbiecom


