# comment

version: 0.1

phases:
  install:
    commands:
      - echo "this is the install phase"
  build:
    commands:
      - echo "this is the build phase"
      - npm install
      - ls -l
      - cd public && ls -l

      # checking aws version
      - aws --version
      - aws s3 ls
      - aws s3 sync ./public/* s3://pipel.sample

      # - aws s3 sync _site/ s3://alexbilbiecom


